"""empty message

Revision ID: d6cd4facd1e8
Revises: 017ba4a29681
Create Date: 2025-01-22 10:46:11.116188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cd4facd1e8'
down_revision: Union[str, None] = '017ba4a29681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_cart_item_id', table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], name='cart_items_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cart_items_product_id_fkey'),
    sa.PrimaryKeyConstraint('cart_item_id', name='cart_items_pkey')
    )
    op.create_index('ix_cart_items_cart_item_id', 'cart_items', ['cart_item_id'], unique=False)
    # ### end Alembic commands ###
