"""empty message

Revision ID: 7e06960922e4
Revises: d6cd4facd1e8
Create Date: 2025-01-22 10:58:09.505947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e06960922e4'
down_revision: Union[str, None] = 'd6cd4facd1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_cart_item_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_cart_product_id', table_name='cart')
    op.drop_index('ix_cart_summary', table_name='cart')
    op.drop_column('cart', 'product_count')
    op.drop_column('cart', 'summary')
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('summary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_cart_summary', 'cart', ['summary'], unique=False)
    op.create_index('ix_cart_product_id', 'cart', ['product_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], name='cart_items_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cart_items_product_id_fkey'),
    sa.PrimaryKeyConstraint('cart_item_id', name='cart_items_pkey')
    )
    op.create_index('ix_cart_items_cart_item_id', 'cart_items', ['cart_item_id'], unique=False)
    # ### end Alembic commands ###
